server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


spring:
  datasource:
    username: root
    password: 827165648
    url: jdbc:mysql://localhost:3306/search?characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart:
      #      单个文件大小
      max-file-size: 30MB
      #      单次请求大小
      max-request-size: 100MB

  jackson:
    time-zone: GMT+8

upload-file-parent-path: /www/wwwroot/search.zjnu404.xyz/static/upload
static-server-root: http://search.zjnu404.xyz:8081/


default-photo-hr: http://search.zjnu404.xyz:8081/head_img/hr.jpg
default-photo-manager: http://search.zjnu404.xyz:8081/head_img/manager.jpg
